development:
  adapter: postgresql
  database: second40app_dev
  username: rth
  password: 

test:
  adapter: postgresql
  database: second40app_dev
  username: rth
  password: 

production:
  adapter: postgresql
  database: second40app_dev
  username: rth
  password: 
